language: node_js
cache:
  directories:
    - "node_modules"
addons:
  chrome: stable
node_js:
  - "6"
  - "8"
env:
  - YARN_OPTS=
  - YARN_OPTS=--no-lockfile
install:
  yarn install $YARN_OPTS
script:
  - npm run lint
  - npm run build
  - npm test
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5 # give xvfb some time to start
